# Interactive graph

```{=html}
<style>
  * {
    font-family: sans-serif;
  }
</style>
```
::: {#plot}
:::

<h2>COVID-19 death counts of top 5 conditions by quarter in 2020-2021</h2>

<!-- Add buttons -->

<button onclick="update(data_20q1)">

2020 Q1

</button>

<button onclick="update(data_20q2)">

2020 Q2

</button>

<button onclick="update(data_20q3)">

2020 Q3

</button>

<button onclick="update(data_20q4)">

2020 Q4

</button>

<button onclick="update(data_21q1)">

2021 Q1

</button>

<button onclick="update(data_21q2)">

2021 Q2

</button>

<button onclick="update(data_21q3)">

2021 Q3

</button>

<button onclick="update(data_21q4)">

2021 Q4

</button>

<!-- Create a div where the graph will take place -->

::: {#my_dataviz}
:::

<p>

The [percentage]{style="color:red;"} shows the change of the current value you're [currently on]{style="color:#6a3d9a;"} compared to the previous value you've [previously clicked]{style="color:#b15928;"}. Note: percentage only shows up once you've clicked on a button, red indicates percentage increase or no change, and green indicates decrease.

The [blue]{style="color:#1f78b4;"} number shows the total number of death of the quarter you're currently on.<br>

Our previous exploration utilized line charts to trace the death counts of the top 5 health conditions over different quarters. While line charts are adept at showcasing overall trends and correlations among variables, they sometimes fall short in accurately representing the finer details, particularly when it comes to small variations in data slopes between consecutive quarters. Moreover, line charts tend to overload viewers with information, where viewers tend to focus more on the macroscopic trends across all time periods, instead of focusing on the microscopic comparisons between 2 consecutive periods.

To address these limitations, we believe the usage of D3 interactive graphs will provide better visualizations on how variables increase and decrease throughout 2 quarters with respect to one another. In our D3 visualization, each quarter plots the top 5 conditions, with the conditions ordered on the x-axis in descending order of death counts.

The D3 animation reveals some insights:

1.  In 2020 Q2, the period of the initial surge of COVID-19, there is a dramatic spike in death counts for all conditions, soaring by almost 1500% from the previous quarter.

2.  2021 Q1 is an interesting quarter. The top 2 conditions of Influenza and Respiratory Failure reach their highest death account in the 2 years. Usually, all 5 variables are positively correlated with one another, yet in 2021 Q1, Hypertensive Disease and Diabetes decrease while Influenza and Respiratory failure increase.

3.  From 2021 Q3 and 2021 Q4, death counts for all conditions become relatively stable.

4.  From 2020 Q1 to 2021 Q4, we can see the massive death counts responsible by each condition at the end of 2 years.

</p>

```{=html}
<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
```
```{=html}
<script src="scripts/myscript.js"></script>
```
