---
title: "Lucy_results"
author: "Lucy"
date: "12/11/2023"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library (tidyverse)
```

# Q1
```{r}
data=read.csv("covid_with_population.csv")
```

```{r}
# data$Year |> unique()
# # sanity check: group should all be by year
# data$Group |> unique()
# # sanity check: these should all have population NAN
# data |> subset(Age.Group=="All Ages")
```

## 2020
```{r}
# copy
geo_df20=data |> filter(Year==2020)
# # sanity check: year should all be 2020
# geo_df20$Year |> unique()
# # sanity check: for Alabama, all conditions' population should be the same
# geo_df20 |> subset(State=="Alabama")
# # check Alabama for covid
# geo_df20 |> subset(State=="Alabama" & Condition.Group=="COVID-19"  )

# filter data: only select covid19, ages except all ages, states != US
geo_df20 = geo_df20 |> subset(Age.Group!="All Ages" & Condition.Group=="COVID-19" & State!="United States")
# geo_df20$State |> unique() |> length()

# for each state, calculate total population & all covid deaths
aggr_20=geo_df20 |> aggregate(cbind(COVID.19.Deaths,TotalPopulation) ~ State, FUN = sum,na.action = na.pass)
# aggr_20$State |> unique() |> length()
# aggr_20 |> filter(State=="New York City" | State=="New York")

# add NYC to NY
aggr_20$COVID.19.Deaths[aggr_20$State == "New York"] <- aggr_20$COVID.19.Deaths[aggr_20$State == "New York"]+aggr_20$COVID.19.Deaths[aggr_20$State == "New York City"]

## sanity check
# aggr_20 |> filter(State=="New York City" | State=="New York")

# calculate rate
aggr_20$death_rate=round(aggr_20$COVID.19.Deaths/(aggr_20$TotalPopulation/100000), digits = 1)
# aggr_20

#import state abbrev
df_states=read_csv("states.csv")

# aggr_20$State |> unique() |> length()
# df_states$State |> unique() |> length()
# join state codes
plot_df_20 <- aggr_20 %>% left_join(df_states,by="State")

# # check is there's nan
# subset(plot_df_20,is.na(Abbreviation))

# drop nan
plot_df_20=plot_df_20 |> drop_na(Abbreviation)
#plot_df_20


```



## 2021
```{r}
# copy
geo_df21=data |> filter(Year==2021)
# # sanity check: year should all be 2021
# geo_df21$Year |> unique()
# # sanity check: for Alabama, all conditions' population should be the same
# geo_df21 |> subset(State=="Alabama")
# # check Alabama for covid
# geo_df21 |> subset(State=="Alabama" & Condition.Group=="COVID-19"  )

# filter data: only select covid19, ages except all ages, states != US
geo_df21 = geo_df21 |> subset(Age.Group!="All Ages" & Condition.Group=="COVID-19" & State!="United States")
# geo_df21$State |> unique() |> length()

# for each state, calculate total population & all covid deaths
aggr_21=geo_df21 |> aggregate(cbind(COVID.19.Deaths,TotalPopulation) ~ State, FUN = sum,na.action = na.pass)
# aggr_21$State |> unique() |> length()
# aggr_21 |> filter(State=="New York City" | State=="New York")

# add NYC to NY
aggr_21$COVID.19.Deaths[aggr_21$State == "New York"] <- aggr_21$COVID.19.Deaths[aggr_21$State == "New York"]+aggr_21$COVID.19.Deaths[aggr_21$State == "New York City"]

# # sanity check
# aggr_21 |> filter(State=="New York City" | State=="New York")

# calculate rate
aggr_21$death_rate=round(aggr_21$COVID.19.Deaths/(aggr_21$TotalPopulation/100000), digits = 1)
# aggr_21

#import state abbrev
df_states=read_csv("states.csv")

# aggr_21$State |> unique() |> length()
# df_states$State |> unique() |> length()
# join state codes
plot_df_21 <- aggr_21 %>% left_join(df_states,by="State")

# # check is there's nan
# subset(plot_df_21,is.na(Abbreviation)) 

# drop nan
plot_df_21=plot_df_21 |> drop_na(Abbreviation)
#plot_df_21


```



https://www.cdc.gov/nchs/pressroom/sosmap/covid19_mortality_final/COVID19.htm
```{r}


# # check NY
# aggr_20 |> filter(State=="New York")
# 
# # check NY death in oriignal dataset
# org=read_csv("Conditions_Contributing_to_COVID-19_Deaths__by_State_and_Age__Provisional_2020-2023.csv")
# org
# org$State |> unique() |> length()
# 
# org |> subset(`Condition Group`=="COVID-19" & State=="New York City" & Year==2020 & Group=='By Year')
# 
# org |> subset(`Condition Group`=="COVID-19" & State=="New York" & Year==2021 & Group=='By Year')
# 
# org_sub=org |> subset(`Age Group`!="All Ages" & `Condition Group`=="COVID-19" & State=="New York" & Year==2020 & Group=='By Year')
# org_sub
# # sum
# sum(org_sub$`COVID-19 Deaths`,na.rm=TRUE)
```

It's far off by around 30% each, but website does note that death rate is adjusted for each state.

We'll see if the ranking and distribution are the same.

https://stackoverflow.com/questions/75028477/draw-choropleth-map-for-us-states-using-plotly

https://plotly.com/r/choropleth-maps/

https://github.com/jasonong/List-of-US-States/blob/master/states.csv


```{r}
# # checks what states are missing
# agg = aggr_20$State |> unique()
# ls_states=df_states$State |> unique()
# 
# agg[!(agg %in% ls_states)]

```



# 2020 plot
```{r}
# create plots
library(plotly)

#common
# give state boundaries a white border
l <- list(color = toRGB("white"), width = 2)
# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)
# 2020 plot
plot_df_20$hover <- with(plot_df_20, paste(State, '<br>', "Death Rate:", death_rate, '<br>', "Death Count:",COVID.19.Deaths))

fig_20 <- plot_geo(plot_df_20, locationmode = 'USA-states')
fig_20 <- fig_20 %>% add_trace(
    z = ~death_rate, locations = ~Abbreviation, text = ~hover,
    color = ~death_rate, colors = 'Purples',
    zmin=20, zmax=230
  )
fig_20 <- fig_20 %>% colorbar(title = "death rate <br> (per 100,000 population)")

fig_20 <- fig_20 %>% layout(
    title = '2020 US COVID-19 Death Rate',
    geo = g
  )

# 2021 plot
plot_df_21$hover <- with(plot_df_21, paste(State, '<br>', "Death Rate:", death_rate, '<br>', "Death Count:",COVID.19.Deaths))

fig_21 <- plot_geo(plot_df_21, locationmode = 'USA-states')
fig_21 <- fig_21 %>% add_trace(
    z = ~death_rate, locations = ~Abbreviation, text = ~hover,
    color = ~death_rate, colors = 'Purples',
    zmin=20, zmax=230
  )
fig_21 <- fig_21 %>% colorbar(title = "death rate  <br> (per 100,000 population)")

fig_21 <- fig_21 %>% layout(
    title = '2021 US COVID-19 Death Rate',
    geo = g
  )

```

```{r}
# find min and max values for sclae
c(plot_df_20$death_rate,plot_df_21$death_rate) |> min() |> print()
c(plot_df_20$death_rate,plot_df_21$death_rate) |> max() |> print()
```

```{r}
fig_20
```
```{r}
fig_21
```
